# Generated by Django 5.0.3 on 2024-03-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
